import test from 'node:test';
import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';

const read=(path:string)=>readFile(new URL(`../${path}`,import.meta.url),'utf8');
test('detail page delegates to the studio and does not render hidden template metadata',async()=>{const source=await read('src/pages/DetailPage.tsx');assert.match(source,/PromptStudioDetail/);assert.doesNotMatch(source,/template\.summary|template\.description|template\.scenarios|template\.name/)});
test('media card dimensions stay fixed at all required breakpoints',async()=>{const css=await read('src/index.css');for(const value of ['480px','400px','600px','504px','680px','584px'])assert.match(css,new RegExp(value));assert.match(css,/\.media-card \{ height: var\(--media-card-height\)/);assert.match(css,/\.media-stage \{ height: var\(--media-stage-height\)/)});
test('removed reference interactions are absent from migrated components',async()=>{const source=(await Promise.all(['src/components/detail/MediaCard.tsx','src/components/detail/PromptStudioDetail.tsx'].map(read))).join('\n');for(const removed of ['handleSelectPreset','showGridHUD','focusPoint','focusDistance','生图引擎在线'])assert.doesNotMatch(source,new RegExp(removed))});
test('manual prompt editing preserves highlights, grows with content, and confirms explicitly',async()=>{const source=await read('src/components/detail/PromptTokenEditor.tsx');assert.match(source,/function ManualPromptHighlight/);assert.match(source,/Math\.max\(112, textarea\.current\.scrollHeight\)/);assert.match(source,/overflow-hidden bg-transparent/);assert.match(source,/onClick=\{confirmEditing\}/);assert.match(source,/aria-label="确认编辑"/);assert.match(source,/onManual\(draft\)/)});
test('inline variable popover uses readable text and a styled scrollbar',async()=>{const source=await read('src/components/detail/InlineVariablePopover.tsx');assert.match(source,/text-slate-900/);assert.match(source,/text-slate-800/);assert.match(source,/prompt-popover-scroll/)});
