import { useEffect, useState } from 'react';
import { fetchActiveGovernanceRules, saveActiveGovernanceRules } from '../../../data/templateGovernanceApi';
import type { GovernanceRuleSet } from '@promptix/shared';

export function GovernanceRulePanel({ onClose }: { onClose: () => void }) {
  const [rules, setRules] = useState<GovernanceRuleSet | null>(null); const [message, setMessage] = useState('');
  useEffect(() => { fetchActiveGovernanceRules().then((value) => setRules(value.rules)).catch((error) => setMessage(error.message)); }, []);
  if (!rules) return <aside className="absolute right-0 top-0 z-30 h-full w-96 border-l bg-white p-5 shadow-xl"><button onClick={onClose}>关闭</button><p>{message || '正在加载规则…'}</p></aside>;
  const setNumber = (value: string, fallback: number) => Number.isFinite(Number(value)) ? Number(value) : fallback;
  return <aside className="absolute right-0 top-0 z-30 h-full w-96 overflow-auto border-l bg-white p-5 shadow-xl"><div className="flex justify-between"><div><h2 className="font-semibold">治理规则</h2><p className="text-xs text-slate-500">保存为新版本，历史运行不受影响</p></div><button onClick={onClose}>关闭</button></div><div className="mt-5 space-y-3"><label className="flex justify-between text-sm">启用定时巡检<input type="checkbox" checked={rules.schedule.enabled} onChange={(e) => setRules({ ...rules, schedule: { ...rules.schedule, enabled: e.target.checked } })}/></label>
    <Field label="Cron" value={rules.schedule.cron} onChange={(v) => setRules({ ...rules, schedule: { ...rules.schedule, cron: v } })}/><Field label="时区" value={rules.schedule.timezone} onChange={(v) => setRules({ ...rules, schedule: { ...rules.schedule, timezone: v } })}/><Field label="扫描上限" value={String(rules.schedule.scanLimit)} onChange={(v) => setRules({ ...rules, schedule: { ...rules.schedule, scanLimit: setNumber(v, rules.schedule.scanLimit) } })}/><Field label="最低自动置信度" value={String(rules.minimumAutoConfidence)} onChange={(v) => setRules({ ...rules, minimumAutoConfidence: setNumber(v, rules.minimumAutoConfidence) })}/><Field label="自动批次上限" value={String(rules.maximumAutoBatchSize)} onChange={(v) => setRules({ ...rules, maximumAutoBatchSize: setNumber(v, rules.maximumAutoBatchSize) })}/><Field label="回滚小时" value={String(rules.rollbackHours)} onChange={(v) => setRules({ ...rules, rollbackHours: setNumber(v, rules.rollbackHours) })}/><Field label="精选槽位" value={String(rules.featured.slotLimit)} onChange={(v) => setRules({ ...rules, featured: { ...rules.featured, slotLimit: setNumber(v, rules.featured.slotLimit) } })}/><Field label="最大替换比例" value={String(rules.featured.maximumReplacementRatio)} onChange={(v) => setRules({ ...rules, featured: { ...rules.featured, maximumReplacementRatio: setNumber(v, rules.featured.maximumReplacementRatio) } })}/><Field label="精选冷却小时" value={String(rules.featured.minimumAdjustmentHours)} onChange={(v) => setRules({ ...rules, featured: { ...rules.featured, minimumAdjustmentHours: setNumber(v, rules.featured.minimumAdjustmentHours) } })}/>
    <button onClick={async () => { try { await saveActiveGovernanceRules(rules); setMessage('规则新版本已保存'); } catch (error) { setMessage(error instanceof Error ? error.message : '保存失败'); } }} className="w-full rounded bg-violet-600 px-3 py-2 text-sm text-white">保存为新版本</button>{message && <p className="text-xs">{message}</p>}</div></aside>;
}
function Field({ label, value, onChange }: { label: string; value: string; onChange: (value: string) => void }) { return <label className="block text-xs text-slate-600">{label}<input value={value} onChange={(e) => onChange(e.target.value)} className="mt-1 w-full rounded border px-2 py-1.5 text-sm"/></label>; }
